apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  annotations:
  name: scan-ci-reports-discfisic-{{ .Values.securityscanci.env }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  volumeMode: Filesystem


